language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

branches:
  only:
    - main

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

install: echo "skip 'gradle assemble' step"

script: 
  # - chmod 777 ./test/run.sh
  # - test/run.sh
  - cd ./springboot-main-slave 
  - pwd
  - ls -la
  - chmod 777 gradlew
  - ./gradlew build coveralls --continue

after_success:
- bash <(curl -s https://codecov.io/bash)>