language: java
jdk:
  - openjdk8

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: 
  - test/run.sh
  # - cd ./springboot-main-slave 
  # - pwd
  # - ls -la
  # - chmod 777 gradlew
  # - ./gradlew clean build