sudo: false
language: java
jdk:
  - openjdk8

branches:
  only:
    - main

script: 
  - chmod 777 ./test/run.sh
  - test/run.sh
  # - cd ./springboot-main-slave 
  # - pwd
  # - ls -la
  # - chmod 777 gradlew
  # - ./gradlew clean build