os: linux
language: java
install: echo "skip './gradlew assemble' step"
dist: trusty
jdk: oraclejdk8

branches:
  only:
    - main

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  - chmod 777 ./scripts/run.sh
  - scripts/run.sh

# after_script:
#   - npm run coveralls

# env:
#   global:
#     - CODECOV_TOKEN="032567f6-ed00-489e-9d50-37f08b2372bd"
#     secure: "Q4mEDUpI9eAUZMkrPPmVjWgGIHLrxoBWNwjpNh88LNM0XgDKc0K6eyG/erPQbNAMxPixaTX18kx4/jnLTJePY4khEdr0fHVvgJhnjHzbijkg9ky8BLgP2wkwfLaDoY/CG2TeFB69Y5dYWFcOis1Fv+BVKrSXQpfHK/y3eE9xak++jXe1bnjoUwLEMdDjmDOXtxYyHicErNucSsbLoLnVA4xb6ZzGuRo78QodsGeWuhrS9urHWOZs8NAzLCCrIo+fej9N63gHYNZ4twaXqdbvAhptCM+h7qO3IQJskw9Q2cBnt3MntYXB9qH4JsrbUpZeBjbyOqfJgXjVA1Mme91kGUJMYk4iRhgpJf+e6u3mookCC+3xWWjkFsH2/U1TqO6WXyjcG1L/ZK+JnarAgz8SGzNICdkG4fEr62NWa/a1RkQdbiJXAeX1N/XN/vrxqVFyNLG2XX1OmObrJCGO4QrI3IY27zvWZHsRZeqet2MVltHjR4xzG+vWWfcCKR1fJif1r30W2Ewtg5lxkcsg6Tpw6ThFkXh9lEa5ThxItsAM/5lTHELPwnNGXvYOfcoYX3toRQjHGI7R6etGNb+/lvhqngT5bK5RQGnnhSR5xDzDN94qtQRvcJLsOonriKjQ9qqT5eQ3ecDE5DEs3aJ9l4R6dCRW2x5PajsI0VJuKlQMIWc="
codecov: true
coveralls: true
env:
  global:
    - CODECOV_TOKEN=7f31adf9-c934-440e-9260-f1df316eb687

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false