os: linux
language: java
install: echo "skip './gradlew assemble' step"
dist: trusty
jdk: oraclejdk8

branches:
  only:
    - main

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  - cd ./springboot-main-slave 
  - chmod 777 gradlew
  - ./gradlew build --continue