language: java
jdk:
  - openjdk8

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: 
  - cd ./springboot-main-slave 
  - gradlew clean build